connect-message: "&e{player} joined the game"
disconnect-message: "&e{player} left the game"
switch-message: "{player} {oldserver} \u00BB {newserver}"
irc-relay:
  message: "&8[IRC]&r <{nick}> {message}"
  me: "&8[IRC]&r &9* &7{nick}&r {action}"
  join: "&8[IRC]&r &7{nick}&r has joined &7{channel}"
  part: "&8[IRC]&r &7{nick}&r has left &7{channel}"
  quit: "&8[IRC]&r &7{nick}&r has quit"
  kick: "&8[IRC]&r &7{nick}&r has kicked &7{victim}&r from &7{channel}&r({reason})"

bot:
  nick: relay-dev
  host: chat.freenode.net
  port: 6667
  prefix: '&'
  channels:
   - '##shadowempire-dev'
